/**
 * Packs the owner's three window-view layers for the Owner Build.
 *
 * Input:  `assets/runtime/window/window-{nebula,planet,station}.webp`, read
 *         only. Each is the source of record and stays byte for byte as
 *         delivered; the script refuses a file whose SHA-256 is not the one
 *         `assets/licenses/ASSET_PROVENANCE.md` records.
 * Output: `src/world/room/window/<name>.b64.txt` (the file, base64, so it
 *         compiles into the bundle and decodes from an in-memory Blob with no
 *         request — see `src/world/assets/meshyAsset.ts` for why) and
 *         `window-layers.json` with the measured size, dimensions and alpha.
 *
 * Nothing is re-encoded: the layers ship exactly as the owner supplied them.
 *
 * Usage: node asset-pipeline/pack-window.mjs
 */
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const appRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = resolve(appRoot, '../..');
const outDir = join(appRoot, 'src/world/room/window');

const LAYERS = {
  nebula: '95e42f54ee818763a5bea34967aeea1ea48c890c92d89cf6c8f82e213a0e05f1',
  planet: 'a0b3c0ba05c60bc8ebd4fafa5e0add657941c18752f6aee21e1c23f833d8a6f1',
  station: '3dbe3453280baf8182ab9b6e8b63d0cb27e35ae03e848aa9c775c03a3b778415',
};

function fail(message) {
  console.error(`pack-window: ${message}`);
  process.exit(1);
}

/** Reads the VP8X canvas size and alpha flag straight from the container. */
function measure(bytes) {
  if (bytes.toString('ascii', 0, 4) !== 'RIFF' || bytes.toString('ascii', 8, 12) !== 'WEBP') {
    fail('not a WebP container');
  }
  if (bytes.toString('ascii', 12, 16) !== 'VP8X') fail('not an extended (VP8X) WebP');
  const flags = bytes[20];
  const width = 1 + (bytes[24] | (bytes[25] << 8) | (bytes[26] << 16));
  const height = 1 + (bytes[27] | (bytes[28] << 8) | (bytes[29] << 16));
  let alphaChunk = false;
  let iccChunk = false;
  let cursor = 30;
  while (cursor + 8 <= bytes.length) {
    const tag = bytes.toString('ascii', cursor, cursor + 4);
    const size = bytes.readUInt32LE(cursor + 4);
    if (tag === 'ALPH') alphaChunk = true;
    if (tag === 'ICCP') iccChunk = true;
    cursor += 8 + size + (size % 2);
  }
  return { width, height, alphaFlag: (flags & 0x10) !== 0, alphaChunk, iccChunk };
}

mkdirSync(outDir, { recursive: true });
const layers = {};
for (const [name, expectedSha] of Object.entries(LAYERS)) {
  const path = `assets/runtime/window/window-${name}.webp`;
  const bytes = readFileSync(join(repoRoot, path));
  const sha256 = createHash('sha256').update(bytes).digest('hex');
  if (sha256 !== expectedSha) {
    fail(`${path}: sha256 ${sha256} is not the registered ${expectedSha}; refusing`);
  }
  const measured = measure(bytes);
  const b64 = bytes.toString('base64');
  writeFileSync(join(outDir, `${name}.b64.txt`), b64);
  layers[name] = {
    path,
    sha256,
    bytes: bytes.length,
    base64Bytes: b64.length,
    mimeType: 'image/webp',
    ...measured,
    provenance: 'assets/licenses/ASSET_PROVENANCE.md',
  };
  console.log(
    `pack-window: ${name} ${bytes.length} B ${measured.width}x${measured.height}` +
      ` alpha=${measured.alphaChunk} icc=${measured.iccChunk} -> base64 ${b64.length} B`,
  );
}
const jsonPath = join(outDir, 'window-layers.json');
writeFileSync(
  jsonPath,
  `${JSON.stringify(
    {
      $comment:
        'Generated by asset-pipeline/pack-window.mjs from the unmodified committed layers. Do not hand-edit; regenerate.',
      layers,
    },
    null,
    2,
  )}\n`,
);
execFileSync(join(repoRoot, 'node_modules/.bin/biome'), ['format', '--write', jsonPath]);
